# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Panda Lab
logo: "assets/logo.png"
description: >- # this means to ignore newlines until "baseurl:"
  PandaLab documentation. PandaLab is an open source solution which helps you to manager fleet of devices and to run automatic tests on them.
baseurl: "/panda-lab" # the subpath of your site, e.g. /blog
url: "https://adeo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
livereload: true
# Build settings
markdown: kramdown
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
repository: adeo/panda-lab
plugins:
  - jekyll-feed

aux_links:
  "PandaLab on GitHub":
    - "//github.com/adeo/panda-lab"

footer_content: "Distributed by an <a href=\"http://www.apache.org/licenses/LICENSE-2.0\">Apache License, Version 2.0.</a>"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
